// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWR4aghTmUGwTzMEAVTyYqe4dx8Fom51A',
    appId: '1:466626241242:web:1e763011a640137deefbe3',
    messagingSenderId: '466626241242',
    projectId: 'splitnest-2aadd',
    authDomain: 'splitnest-2aadd.firebaseapp.com',
    storageBucket: 'splitnest-2aadd.firebasestorage.app',
    measurementId: 'G-YCWHFZWM63',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5ZiziBthlrnBZMunei8Cx59eHIFMY-lA',
    appId: '1:466626241242:android:1095cee1184f36deeefbe3',
    messagingSenderId: '466626241242',
    projectId: 'splitnest-2aadd',
    storageBucket: 'splitnest-2aadd.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWR4aghTmUGwTzMEAVTyYqe4dx8Fom51A',
    appId: '1:466626241242:web:e07ac4b2b3f0d1e3eefbe3',
    messagingSenderId: '466626241242',
    projectId: 'splitnest-2aadd',
    authDomain: 'splitnest-2aadd.firebaseapp.com',
    storageBucket: 'splitnest-2aadd.firebasestorage.app',
    measurementId: 'G-FGMWWGH7Q1',
  );
}
